package org.esdee.otrs.model;

import java.util.ArrayList;
import java.util.List;

import org.apache.poi.xssf.usermodel.XSSFColor;

public class WebColors {

	public WebColors() {}
	
	public WebColors(XSSFColor color) {
		this.color = color;
	}
	
	public XSSFColor color;
	public XSSFColor pink = new XSSFColor(new java.awt.Color(255, 192, 203));
	public XSSFColor lightPink = new XSSFColor(new java.awt.Color(255, 182, 193));
	public XSSFColor hotPink = new XSSFColor(new java.awt.Color(255, 105, 180));
	public XSSFColor deepPink = new XSSFColor(new java.awt.Color(255, 20, 147));
	public XSSFColor paleVioletRed = new XSSFColor(new java.awt.Color(219, 112, 147));
	public XSSFColor mediumVioletRed = new XSSFColor(new java.awt.Color(199, 21, 133));
	public XSSFColor lightSalmon = new XSSFColor(new java.awt.Color(255, 160, 122));
	public XSSFColor salmon = new XSSFColor(new java.awt.Color(250, 128, 114));
	public XSSFColor darkSalmon = new XSSFColor(new java.awt.Color(233, 150, 122));
	public XSSFColor lightCoral = new XSSFColor(new java.awt.Color(240, 128, 128));
	public XSSFColor indianRed = new XSSFColor(new java.awt.Color(205, 92, 92));
	public XSSFColor crimson = new XSSFColor(new java.awt.Color(220, 20, 60));
	public XSSFColor firebrick = new XSSFColor(new java.awt.Color(178, 34, 34));
	public XSSFColor darkRed = new XSSFColor(new java.awt.Color(139, 0, 0));
	public XSSFColor red = new XSSFColor(new java.awt.Color(255, 0, 0));
	public XSSFColor alizarinCrimson = new XSSFColor(new java.awt.Color(227, 38, 54));
	public XSSFColor amaranth = new XSSFColor(new java.awt.Color(229, 43, 80));
	public XSSFColor amarantPink = new XSSFColor(new java.awt.Color(241, 156, 187));
	public XSSFColor radicalRed = new XSSFColor(new java.awt.Color(255, 53, 94));
	public XSSFColor amaranthPurple = new XSSFColor(new java.awt.Color(171, 39, 79));
	public XSSFColor amaranthMP = new XSSFColor(new java.awt.Color(159, 43, 104));
	public XSSFColor bloodRed = new XSSFColor(new java.awt.Color(102, 0, 0));
	public XSSFColor burgundy = new XSSFColor(new java.awt.Color(144, 0, 32));
	public XSSFColor candyAppleRed = new XSSFColor(new java.awt.Color(255, 8, 0));
	public XSSFColor candyPink = new XSSFColor(new java.awt.Color(228, 113, 122));
	public XSSFColor cardinalRed = new XSSFColor(new java.awt.Color(196, 30, 58));
	public XSSFColor fresnoStateCardinal = new XSSFColor(new java.awt.Color(196, 18, 48));
	public XSSFColor uscCardinalRed = new XSSFColor(new java.awt.Color(153, 27, 30));
	public XSSFColor stanfordRed = new XSSFColor(new java.awt.Color(140, 21, 21));
	public XSSFColor carmineRed = new XSSFColor(new java.awt.Color(150, 0, 24));
	public XSSFColor wildWatermelonRed = new XSSFColor(new java.awt.Color(252, 108, 133));
	public XSSFColor ceriseRed = new XSSFColor(new java.awt.Color(229, 49, 99));
	public XSSFColor hollywoodCerise = new XSSFColor(new java.awt.Color(244, 0, 161));
	public XSSFColor crayolaCerise = new XSSFColor(new java.awt.Color(218, 50, 135));
	public XSSFColor irresistibleRed = new XSSFColor(new java.awt.Color(179, 68, 108));
	public XSSFColor munsellRed = new XSSFColor(new java.awt.Color(242, 0, 60));
	public XSSFColor pantoneRed = new XSSFColor(new java.awt.Color(237, 41, 57));
	public XSSFColor crayolaRed = new XSSFColor(new java.awt.Color(238, 32, 77));
	public XSSFColor scarletRed = new XSSFColor(new java.awt.Color(255, 36, 0));
	public XSSFColor imperialRed = new XSSFColor(new java.awt.Color(237, 41, 57));
	public XSSFColor rubyRed = new XSSFColor(new java.awt.Color(224, 17, 95));
	public XSSFColor rustyRed = new XSSFColor(new java.awt.Color(218, 44, 67));
	public XSSFColor fireEnginRed = new XSSFColor(new java.awt.Color(206, 32, 41));
	public XSSFColor chiliRed = new XSSFColor(new java.awt.Color(226, 61, 40));
	public XSSFColor cornellRed = new XSSFColor(new java.awt.Color(179, 27, 27));
	public XSSFColor madderRed = new XSSFColor(new java.awt.Color(165, 0, 33));
	public XSSFColor redwoodRed = new XSSFColor(new java.awt.Color(164, 90, 82));
	public XSSFColor chocolateCosmosRed = new XSSFColor(new java.awt.Color(88, 17, 26));
	public XSSFColor turkeyRed = new XSSFColor(new java.awt.Color(169, 17, 1));
	public XSSFColor cinnabarRed = new XSSFColor(new java.awt.Color(228, 77, 48));
	public XSSFColor coquelicotRed = new XSSFColor(new java.awt.Color(255, 56, 0));
	public XSSFColor mahoganyRed = new XSSFColor(new java.awt.Color(192, 64, 0));
	public XSSFColor raspberryRed = new XSSFColor(new java.awt.Color(227, 11, 92));
	public XSSFColor venetianRed = new XSSFColor(new java.awt.Color(200, 8, 21));
	public XSSFColor vermilionRed = new XSSFColor(new java.awt.Color(227, 66, 52));
	public XSSFColor rossoCorsa = new XSSFColor(new java.awt.Color(204, 0, 0));
	public XSSFColor orangeRed = new XSSFColor(new java.awt.Color(255, 69, 0));
	public XSSFColor tomato = new XSSFColor(new java.awt.Color(255, 99, 71));
	public XSSFColor coral = new XSSFColor(new java.awt.Color(255, 127, 80));
	public XSSFColor darkOrange = new XSSFColor(new java.awt.Color(255, 140, 0));
	public XSSFColor orange = new XSSFColor(new java.awt.Color(255, 165, 0));
	public XSSFColor yellow = new XSSFColor(new java.awt.Color(255, 255, 0));
	public XSSFColor lightYellow = new XSSFColor(new java.awt.Color(255, 255, 224));
	public XSSFColor lemonChiffon = new XSSFColor(new java.awt.Color(255, 250, 205));
	public XSSFColor lightGoldenrodYellow = new XSSFColor(new java.awt.Color(250, 250, 210));
	public XSSFColor papayaWhip = new XSSFColor(new java.awt.Color(255, 239, 213));
	public XSSFColor moccasin = new XSSFColor(new java.awt.Color(255, 228, 181));
	public XSSFColor peachPuff = new XSSFColor(new java.awt.Color(255, 218, 185));
	public XSSFColor paleGoldenrod = new XSSFColor(new java.awt.Color(238, 232, 170));
	public XSSFColor khaki = new XSSFColor(new java.awt.Color(240, 230, 140));
	public XSSFColor darkKakhi = new XSSFColor(new java.awt.Color(189, 183, 107));
	public XSSFColor gold = new XSSFColor(new java.awt.Color(255, 215, 0));
	public XSSFColor cornsilk = new XSSFColor(new java.awt.Color(255, 248, 220));
	public XSSFColor blanchedAlmond = new XSSFColor(new java.awt.Color(255, 235, 205));
	public XSSFColor bisque = new XSSFColor(new java.awt.Color(255, 228, 196));
	public XSSFColor navajoWhite = new XSSFColor(new java.awt.Color(255, 222, 173));
	public XSSFColor wheat = new XSSFColor(new java.awt.Color(245, 222, 179));
	public XSSFColor burlywood = new XSSFColor(new java.awt.Color(222, 184, 135));
	public XSSFColor tan = new XSSFColor(new java.awt.Color(210, 180, 140));
	public XSSFColor rosyBrown = new XSSFColor(new java.awt.Color(188, 143, 143));
	public XSSFColor sandyBrown = new XSSFColor(new java.awt.Color(244, 164, 96));
	public XSSFColor goldenrod = new XSSFColor(new java.awt.Color(218, 165, 32));
	public XSSFColor darkGoldenrod = new XSSFColor(new java.awt.Color(184, 134, 11));
	public XSSFColor peru = new XSSFColor(new java.awt.Color(205, 133, 63));
	public XSSFColor chocolate = new XSSFColor(new java.awt.Color(210, 105, 30));
	public XSSFColor saddleBrown = new XSSFColor(new java.awt.Color(139, 69, 19));
	public XSSFColor sienna = new XSSFColor(new java.awt.Color(160, 82, 45));
	public XSSFColor brown = new XSSFColor(new java.awt.Color(165, 42, 42));
	public XSSFColor maroon = new XSSFColor(new java.awt.Color(128, 0, 0));
	public XSSFColor darkOliveGreen = new XSSFColor(new java.awt.Color(85, 107, 47));
	public XSSFColor olive = new XSSFColor(new java.awt.Color(128, 128, 0));
	public XSSFColor oliveDrab = new XSSFColor(new java.awt.Color(107, 142, 35));
	public XSSFColor yellowGreen = new XSSFColor(new java.awt.Color(154, 205, 50));
	public XSSFColor limeGreen = new XSSFColor(new java.awt.Color(50, 205, 50));
	public XSSFColor lime = new XSSFColor(new java.awt.Color(0, 255, 0));
	public XSSFColor lawnGreen = new XSSFColor(new java.awt.Color(124, 252, 0));
	public XSSFColor chartreuse = new XSSFColor(new java.awt.Color(127, 255, 0));
	public XSSFColor greenYellow = new XSSFColor(new java.awt.Color(173, 255, 47));
	public XSSFColor springGreen = new XSSFColor(new java.awt.Color(0, 255, 127));
	public XSSFColor mediumSpringGreen = new XSSFColor(new java.awt.Color(0, 250, 154));
	public XSSFColor lightGreen = new XSSFColor(new java.awt.Color(144, 238, 144));
	public XSSFColor paleGreen = new XSSFColor(new java.awt.Color(152, 251, 152));
	public XSSFColor darkSeaGreen = new XSSFColor(new java.awt.Color(143, 188, 143));
	public XSSFColor mediumAquamarine = new XSSFColor(new java.awt.Color(102, 205, 170));
	public XSSFColor mediumSeaGreen = new XSSFColor(new java.awt.Color(60, 179, 113));
	public XSSFColor seaGreen = new XSSFColor(new java.awt.Color(46, 139, 87));
	public XSSFColor forestGreen = new XSSFColor(new java.awt.Color(34, 139, 34));
	public XSSFColor green = new XSSFColor(new java.awt.Color(0, 128, 0));
	public XSSFColor darkGreen = new XSSFColor(new java.awt.Color(0, 100, 0));
	public XSSFColor aqua = new XSSFColor(new java.awt.Color(0, 255, 255));
	public XSSFColor cyan = new XSSFColor(new java.awt.Color(0, 255, 255));
	public XSSFColor lightCyan = new XSSFColor(new java.awt.Color(224, 255, 255));
	public XSSFColor paleTurquoise = new XSSFColor(new java.awt.Color(175, 238, 238));
	public XSSFColor aquaMarine = new XSSFColor(new java.awt.Color(127, 255, 212));
	public XSSFColor turquoise = new XSSFColor(new java.awt.Color(64, 224, 208));
	public XSSFColor mediumTurqoise = new XSSFColor(new java.awt.Color(72, 209, 204));
	public XSSFColor darkTurquoise = new XSSFColor(new java.awt.Color(0, 206, 209));
	public XSSFColor lightSeaGreen = new XSSFColor(new java.awt.Color(32, 178, 170));
	public XSSFColor airForceBlue = new XSSFColor(new java.awt.Color(93, 138, 168));
	public XSSFColor spaceCadetBlue = new XSSFColor(new java.awt.Color(29, 41, 81));
	public XSSFColor fluorescentBlue = new XSSFColor(new java.awt.Color(21, 244, 238));
	public XSSFColor azureWhite = new XSSFColor(new java.awt.Color(0, 127, 255));
	public XSSFColor babyBlue = new XSSFColor(new java.awt.Color(137, 207, 240));
	public XSSFColor blueDeFrance = new XSSFColor(new java.awt.Color(49, 140, 231));
	public XSSFColor blueGray = new XSSFColor(new java.awt.Color(102, 153, 204));
	public XSSFColor bondiBlue = new XSSFColor(new java.awt.Color(13, 152, 186));
	public XSSFColor argentinianBlue = new XSSFColor(new java.awt.Color(108, 180, 238));
	public XSSFColor byzantineBlue = new XSSFColor(new java.awt.Color(52, 87, 213));
	public XSSFColor capriBlue = new XSSFColor(new java.awt.Color(0, 191, 255));
	public XSSFColor carolinaBlue = new XSSFColor(new java.awt.Color(75, 156, 211));
	public XSSFColor celesteBlue = new XSSFColor(new java.awt.Color(178, 255, 255));
	public XSSFColor ceruleanBlue = new XSSFColor(new java.awt.Color(0, 123, 167));
	public XSSFColor cobaltBlue = new XSSFColor(new java.awt.Color(0, 71, 171));
	public XSSFColor columbiaBlue = new XSSFColor(new java.awt.Color(185, 217, 235));
	public XSSFColor denimBlue = new XSSFColor(new java.awt.Color(63, 0, 255));
	public XSSFColor dukeBlue = new XSSFColor(new java.awt.Color(0, 26, 87));
	public XSSFColor egyptianBlue = new XSSFColor(new java.awt.Color(16, 52, 166));
	public XSSFColor electricBlue = new XSSFColor(new java.awt.Color(125, 249, 255));
	public XSSFColor morningBlue = new XSSFColor(new java.awt.Color(141, 163, 153));
	public XSSFColor glacousBlue = new XSSFColor(new java.awt.Color(96, 130, 182));
	public XSSFColor electricIndigoBlue = new XSSFColor(new java.awt.Color(111, 0, 255));
	public XSSFColor iceBlue = new XSSFColor(new java.awt.Color(153, 255, 255));
	public XSSFColor marianBlue = new XSSFColor(new java.awt.Color(255, 235, 238));
	public XSSFColor mayaBlue = new XSSFColor(new java.awt.Color(115, 194, 251));
	public XSSFColor neonBlue = new XSSFColor(new java.awt.Color(70, 102, 255));
	public XSSFColor crayolaBlue = new XSSFColor(new java.awt.Color(31, 117, 254));
	public XSSFColor ruddyBlue = new XSSFColor(new java.awt.Color(118, 171, 223));
	public XSSFColor spanishBlue = new XSSFColor(new java.awt.Color(0, 112, 184));
	public XSSFColor libertyBlue = new XSSFColor(new java.awt.Color(84, 90, 167));
	public XSSFColor delftBlue = new XSSFColor(new java.awt.Color(31, 48, 94));
	public XSSFColor duckBlue = new XSSFColor(new java.awt.Color(0, 119, 145));
	public XSSFColor resolutionBlue = new XSSFColor(new java.awt.Color(0, 35, 185));
	public XSSFColor polynesianBlue = new XSSFColor(new java.awt.Color(34, 76, 152));
	public XSSFColor independenceBlue = new XSSFColor(new java.awt.Color(76, 81, 109));
	public XSSFColor cadetBlue = new XSSFColor(new java.awt.Color(95, 158, 160));
	public XSSFColor darkCyan = new XSSFColor(new java.awt.Color(0, 139, 139));
	public XSSFColor teal = new XSSFColor(new java.awt.Color(0, 128, 128));
	public XSSFColor lightSteelBlue = new XSSFColor(new java.awt.Color(176, 196, 222));
	public XSSFColor powderBlue = new XSSFColor(new java.awt.Color(176, 224, 230));
	public XSSFColor lightBlue = new XSSFColor(new java.awt.Color(173, 216, 230));
	public XSSFColor skyBlue = new XSSFColor(new java.awt.Color(135, 206, 235));
	public XSSFColor lightSkyBlue = new XSSFColor(new java.awt.Color(135, 206, 250));
	public XSSFColor deepSkyBlue = new XSSFColor(new java.awt.Color(0, 191, 255));
	public XSSFColor dodgerBlue = new XSSFColor(new java.awt.Color(30, 144, 255));
	public XSSFColor cornflowerBlue = new XSSFColor(new java.awt.Color(100, 149, 237));
	public XSSFColor steelBlue = new XSSFColor(new java.awt.Color(70, 130, 180));
	public XSSFColor royalBlue = new XSSFColor(new java.awt.Color(65, 105, 225));
	public XSSFColor blue = new XSSFColor(new java.awt.Color(0, 0, 255));
	public XSSFColor mediumBlue = new XSSFColor(new java.awt.Color(0, 0, 205));
	public XSSFColor darkBlue = new XSSFColor(new java.awt.Color(0, 0, 139));
	public XSSFColor navy = new XSSFColor(new java.awt.Color(0, 0, 128));
	public XSSFColor midnightBlue = new XSSFColor(new java.awt.Color(25, 25, 112));
	public XSSFColor lavender = new XSSFColor(new java.awt.Color(230, 230, 250));
	public XSSFColor thistle = new XSSFColor(new java.awt.Color(216, 191, 216));
	public XSSFColor plum = new XSSFColor(new java.awt.Color(221, 160, 221));
	public XSSFColor violet = new XSSFColor(new java.awt.Color(238, 130, 238));
	public XSSFColor orchid = new XSSFColor(new java.awt.Color(218, 112, 214));
	public XSSFColor fuchsia = new XSSFColor(new java.awt.Color(255, 0, 255));
	public XSSFColor magenta = new XSSFColor(new java.awt.Color(255, 0, 255));
	public XSSFColor mediumOrchid = new XSSFColor(new java.awt.Color(186, 85, 211));
	public XSSFColor mediumPurple = new XSSFColor(new java.awt.Color(147, 112, 219));
	public XSSFColor blueViolet = new XSSFColor(new java.awt.Color(138, 43, 226));
	public XSSFColor darkViolet = new XSSFColor(new java.awt.Color(148, 0, 211));
	public XSSFColor darkOrchid = new XSSFColor(new java.awt.Color(153, 50, 204));
	public XSSFColor darkMagenta = new XSSFColor(new java.awt.Color(139, 0, 139));
	public XSSFColor purple = new XSSFColor(new java.awt.Color(128, 0, 128));
	public XSSFColor indigo = new XSSFColor(new java.awt.Color(75, 0, 130));
	public XSSFColor darkSlateBlue = new XSSFColor(new java.awt.Color(72, 61, 139));
	public XSSFColor slateBlue = new XSSFColor(new java.awt.Color(106, 90, 205));
	public XSSFColor mediumSlateBlue = new XSSFColor(new java.awt.Color(123, 104, 238));
	public XSSFColor white = new XSSFColor(new java.awt.Color(255, 255, 255));
	public XSSFColor snow = new XSSFColor(new java.awt.Color(255, 250, 250));
	public XSSFColor honeydew = new XSSFColor(new java.awt.Color(240, 255, 240));
	public XSSFColor mintCream = new XSSFColor(new java.awt.Color(245, 255, 250));
	public XSSFColor azure = new XSSFColor(new java.awt.Color(240, 255, 255));
	public XSSFColor aliceBlue = new XSSFColor(new java.awt.Color(240, 248, 255));
	public XSSFColor ghostWhite = new XSSFColor(new java.awt.Color(248, 248, 255));
	public XSSFColor whiteSmoke = new XSSFColor(new java.awt.Color(245, 245, 245));
	public XSSFColor seashell = new XSSFColor(new java.awt.Color(255, 245, 238));
	public XSSFColor beige = new XSSFColor(new java.awt.Color(245, 245, 220));
	public XSSFColor oldLace = new XSSFColor(new java.awt.Color(253, 245, 230));
	public XSSFColor floralWhite = new XSSFColor(new java.awt.Color(255, 250, 240));
	public XSSFColor ivory = new XSSFColor(new java.awt.Color(255, 255, 240));
	public XSSFColor antiqueWhite = new XSSFColor(new java.awt.Color(250, 235, 215));
	public XSSFColor linen = new XSSFColor(new java.awt.Color(250, 240, 230));
	public XSSFColor lavenderBlush = new XSSFColor(new java.awt.Color(255, 240, 245));
	public XSSFColor mistyRose = new XSSFColor(new java.awt.Color(255, 228, 225));
	public XSSFColor gainsboro = new XSSFColor(new java.awt.Color(220, 220, 220));
	public XSSFColor lightGray = new XSSFColor(new java.awt.Color(211, 211, 211));
	public XSSFColor silver = new XSSFColor(new java.awt.Color(192, 192, 192));
	public XSSFColor darkGray = new XSSFColor(new java.awt.Color(169, 169, 169));
	public XSSFColor gray = new XSSFColor(new java.awt.Color(128, 128, 128));
	public XSSFColor dimGray = new XSSFColor(new java.awt.Color(105, 105, 105));
	public XSSFColor lightSlateGray = new XSSFColor(new java.awt.Color(119, 136, 153));
	public XSSFColor slateGray = new XSSFColor(new java.awt.Color(112, 128, 144));
	public XSSFColor darkSlateGray = new XSSFColor(new java.awt.Color(47, 79, 79));
	public XSSFColor black = new XSSFColor(new java.awt.Color(0, 0, 0));
	
	public List<XSSFColor> xssfColorList() {
		List<XSSFColor> xssfColorList = new ArrayList<XSSFColor>();
		
		xssfColorList.add(new WebColors().pink);
		xssfColorList.add(new WebColors().lightPink);
		xssfColorList.add(new WebColors().hotPink);
		xssfColorList.add(new WebColors().deepPink);
		xssfColorList.add(new WebColors().paleVioletRed);
		xssfColorList.add(new WebColors().mediumVioletRed);
		xssfColorList.add(new WebColors().lightSalmon);
		xssfColorList.add(new WebColors().salmon);
		xssfColorList.add(new WebColors().darkSalmon);
		xssfColorList.add(new WebColors().lightCoral);
		xssfColorList.add(new WebColors().indianRed);
		xssfColorList.add(new WebColors().crimson);
		xssfColorList.add(new WebColors().firebrick);
		xssfColorList.add(new WebColors().darkRed);
		xssfColorList.add(new WebColors().red);
		xssfColorList.add(new WebColors().alizarinCrimson);
		xssfColorList.add(new WebColors().amaranth);
		xssfColorList.add(new WebColors().amarantPink);
		xssfColorList.add(new WebColors().radicalRed);
		xssfColorList.add(new WebColors().amaranthPurple);
		xssfColorList.add(new WebColors().amaranthMP);
		xssfColorList.add(new WebColors().bloodRed);
		xssfColorList.add(new WebColors().burgundy);
		xssfColorList.add(new WebColors().candyAppleRed);
		xssfColorList.add(new WebColors().candyPink);
		xssfColorList.add(new WebColors().cardinalRed);
		xssfColorList.add(new WebColors().fresnoStateCardinal);
		xssfColorList.add(new WebColors().uscCardinalRed);
		xssfColorList.add(new WebColors().stanfordRed);
		xssfColorList.add(new WebColors().carmineRed);
		xssfColorList.add(new WebColors().wildWatermelonRed);
		xssfColorList.add(new WebColors().ceriseRed);
		xssfColorList.add(new WebColors().hollywoodCerise);
		xssfColorList.add(new WebColors().crayolaCerise);
		xssfColorList.add(new WebColors().irresistibleRed);
		xssfColorList.add(new WebColors().munsellRed);
		xssfColorList.add(new WebColors().pantoneRed);
		xssfColorList.add(new WebColors().crayolaRed);
		xssfColorList.add(new WebColors().scarletRed);
		xssfColorList.add(new WebColors().imperialRed);
		xssfColorList.add(new WebColors().rubyRed);
		xssfColorList.add(new WebColors().rustyRed);
		xssfColorList.add(new WebColors().fireEnginRed);
		xssfColorList.add(new WebColors().chiliRed);
		xssfColorList.add(new WebColors().cornellRed);
		xssfColorList.add(new WebColors().madderRed);
		xssfColorList.add(new WebColors().redwoodRed);
		xssfColorList.add(new WebColors().chocolateCosmosRed);
		xssfColorList.add(new WebColors().turkeyRed);
		xssfColorList.add(new WebColors().cinnabarRed);
		xssfColorList.add(new WebColors().coquelicotRed);
		xssfColorList.add(new WebColors().mahoganyRed);
		xssfColorList.add(new WebColors().raspberryRed);
		xssfColorList.add(new WebColors().venetianRed);
		xssfColorList.add(new WebColors().vermilionRed);
		xssfColorList.add(new WebColors().rossoCorsa);
		xssfColorList.add(new WebColors().orangeRed);
		xssfColorList.add(new WebColors().tomato);
		xssfColorList.add(new WebColors().coral);
		xssfColorList.add(new WebColors().darkOrange);
		xssfColorList.add(new WebColors().orange);
		xssfColorList.add(new WebColors().yellow);
		xssfColorList.add(new WebColors().lightYellow);
		xssfColorList.add(new WebColors().lemonChiffon);
		xssfColorList.add(new WebColors().lightGoldenrodYellow);
		xssfColorList.add(new WebColors().papayaWhip);
		xssfColorList.add(new WebColors().moccasin);
		xssfColorList.add(new WebColors().peachPuff);
		xssfColorList.add(new WebColors().paleGoldenrod);
		xssfColorList.add(new WebColors().khaki);
		xssfColorList.add(new WebColors().darkKakhi);
		xssfColorList.add(new WebColors().gold);
		xssfColorList.add(new WebColors().cornsilk);
		xssfColorList.add(new WebColors().blanchedAlmond);
		xssfColorList.add(new WebColors().bisque);
		xssfColorList.add(new WebColors().navajoWhite);
		xssfColorList.add(new WebColors().wheat);
		xssfColorList.add(new WebColors().burlywood);
		xssfColorList.add(new WebColors().tan);
		xssfColorList.add(new WebColors().rosyBrown);
		xssfColorList.add(new WebColors().sandyBrown);
		xssfColorList.add(new WebColors().goldenrod);
		xssfColorList.add(new WebColors().darkGoldenrod);
		xssfColorList.add(new WebColors().peru);
		xssfColorList.add(new WebColors().chocolate);
		xssfColorList.add(new WebColors().saddleBrown);
		xssfColorList.add(new WebColors().sienna);
		xssfColorList.add(new WebColors().brown);
		xssfColorList.add(new WebColors().maroon);
		xssfColorList.add(new WebColors().darkOliveGreen);
		xssfColorList.add(new WebColors().olive);
		xssfColorList.add(new WebColors().oliveDrab);
		xssfColorList.add(new WebColors().yellowGreen);
		xssfColorList.add(new WebColors().limeGreen);
		xssfColorList.add(new WebColors().lime);
		xssfColorList.add(new WebColors().lawnGreen);
		xssfColorList.add(new WebColors().chartreuse);
		xssfColorList.add(new WebColors().greenYellow);
		xssfColorList.add(new WebColors().springGreen);
		xssfColorList.add(new WebColors().mediumSpringGreen);
		xssfColorList.add(new WebColors().lightGreen);
		xssfColorList.add(new WebColors().paleGreen);
		xssfColorList.add(new WebColors().darkSeaGreen);
		xssfColorList.add(new WebColors().mediumAquamarine);
		xssfColorList.add(new WebColors().mediumSeaGreen);
		xssfColorList.add(new WebColors().seaGreen);
		xssfColorList.add(new WebColors().forestGreen);
		xssfColorList.add(new WebColors().green);
		xssfColorList.add(new WebColors().darkGreen);
		xssfColorList.add(new WebColors().aqua);
		xssfColorList.add(new WebColors().cyan);
		xssfColorList.add(new WebColors().lightCyan);
		xssfColorList.add(new WebColors().paleTurquoise);
		xssfColorList.add(new WebColors().aquaMarine);
		xssfColorList.add(new WebColors().turquoise);
		xssfColorList.add(new WebColors().mediumTurqoise);
		xssfColorList.add(new WebColors().darkTurquoise);
		xssfColorList.add(new WebColors().lightSeaGreen);
		xssfColorList.add(new WebColors().airForceBlue);
		xssfColorList.add(new WebColors().spaceCadetBlue);
		xssfColorList.add(new WebColors().fluorescentBlue);
		xssfColorList.add(new WebColors().azureWhite);
		xssfColorList.add(new WebColors().babyBlue);
		xssfColorList.add(new WebColors().blueDeFrance);
		xssfColorList.add(new WebColors().blueGray);
		xssfColorList.add(new WebColors().bondiBlue);
		xssfColorList.add(new WebColors().argentinianBlue);
		xssfColorList.add(new WebColors().byzantineBlue);
		xssfColorList.add(new WebColors().capriBlue);
		xssfColorList.add(new WebColors().carolinaBlue);
		xssfColorList.add(new WebColors().celesteBlue);
		xssfColorList.add(new WebColors().ceruleanBlue);
		xssfColorList.add(new WebColors().cobaltBlue);
		xssfColorList.add(new WebColors().columbiaBlue);
		xssfColorList.add(new WebColors().denimBlue);
		xssfColorList.add(new WebColors().dukeBlue);
		xssfColorList.add(new WebColors().egyptianBlue);
		xssfColorList.add(new WebColors().electricBlue);
		xssfColorList.add(new WebColors().morningBlue);
		xssfColorList.add(new WebColors().glacousBlue);
		xssfColorList.add(new WebColors().electricIndigoBlue);
		xssfColorList.add(new WebColors().iceBlue);
		xssfColorList.add(new WebColors().marianBlue);
		xssfColorList.add(new WebColors().mayaBlue);
		xssfColorList.add(new WebColors().neonBlue);
		xssfColorList.add(new WebColors().crayolaBlue);
		xssfColorList.add(new WebColors().ruddyBlue);
		xssfColorList.add(new WebColors().spanishBlue);
		xssfColorList.add(new WebColors().libertyBlue);
		xssfColorList.add(new WebColors().delftBlue);
		xssfColorList.add(new WebColors().duckBlue);
		xssfColorList.add(new WebColors().resolutionBlue);
		xssfColorList.add(new WebColors().polynesianBlue);
		xssfColorList.add(new WebColors().independenceBlue);
		xssfColorList.add(new WebColors().cadetBlue);
		xssfColorList.add(new WebColors().darkCyan);
		xssfColorList.add(new WebColors().teal);
		xssfColorList.add(new WebColors().lightSteelBlue);
		xssfColorList.add(new WebColors().powderBlue);
		xssfColorList.add(new WebColors().lightBlue);
		xssfColorList.add(new WebColors().skyBlue);
		xssfColorList.add(new WebColors().lightSkyBlue);
		xssfColorList.add(new WebColors().deepSkyBlue);
		xssfColorList.add(new WebColors().dodgerBlue);
		xssfColorList.add(new WebColors().cornflowerBlue);
		xssfColorList.add(new WebColors().steelBlue);
		xssfColorList.add(new WebColors().royalBlue);
		xssfColorList.add(new WebColors().blue);
		xssfColorList.add(new WebColors().mediumBlue);
		xssfColorList.add(new WebColors().darkBlue);
		xssfColorList.add(new WebColors().navy);
		xssfColorList.add(new WebColors().midnightBlue);
		xssfColorList.add(new WebColors().lavender);
		xssfColorList.add(new WebColors().thistle);
		xssfColorList.add(new WebColors().plum);
		xssfColorList.add(new WebColors().violet);
		xssfColorList.add(new WebColors().orchid);
		xssfColorList.add(new WebColors().fuchsia);
		xssfColorList.add(new WebColors().magenta);
		xssfColorList.add(new WebColors().mediumOrchid);
		xssfColorList.add(new WebColors().mediumPurple);
		xssfColorList.add(new WebColors().blueViolet);
		xssfColorList.add(new WebColors().darkViolet);
		xssfColorList.add(new WebColors().darkOrchid);
		xssfColorList.add(new WebColors().darkMagenta);
		xssfColorList.add(new WebColors().purple);
		xssfColorList.add(new WebColors().indigo);
		xssfColorList.add(new WebColors().darkSlateBlue);
		xssfColorList.add(new WebColors().slateBlue);
		xssfColorList.add(new WebColors().mediumSlateBlue);
		xssfColorList.add(new WebColors().white);
		xssfColorList.add(new WebColors().snow);
		xssfColorList.add(new WebColors().honeydew);
		xssfColorList.add(new WebColors().mintCream);
		xssfColorList.add(new WebColors().azure);
		xssfColorList.add(new WebColors().aliceBlue);
		xssfColorList.add(new WebColors().ghostWhite);
		xssfColorList.add(new WebColors().whiteSmoke);
		xssfColorList.add(new WebColors().seashell);
		xssfColorList.add(new WebColors().beige);
		xssfColorList.add(new WebColors().oldLace);
		xssfColorList.add(new WebColors().floralWhite);
		xssfColorList.add(new WebColors().ivory);
		xssfColorList.add(new WebColors().antiqueWhite);
		xssfColorList.add(new WebColors().linen);
		xssfColorList.add(new WebColors().lavenderBlush);
		xssfColorList.add(new WebColors().mistyRose);
		xssfColorList.add(new WebColors().gainsboro);
		xssfColorList.add(new WebColors().lightGray);
		xssfColorList.add(new WebColors().silver);
		xssfColorList.add(new WebColors().darkGray);
		xssfColorList.add(new WebColors().gray);
		xssfColorList.add(new WebColors().dimGray);
		xssfColorList.add(new WebColors().lightSlateGray);
		xssfColorList.add(new WebColors().slateGray);
		xssfColorList.add(new WebColors().darkSlateGray);
		xssfColorList.add(new WebColors().black);
		
		return xssfColorList;
		
	}
}
